### ISSUE TITLE
reopen https://github.com/dysath/seat-billing/issues/2

### ISSUE THREAD

**Issue by BrownStar** [dysath/seat-billing#4]
When a user first logs into seat, it generates their 'main group'. however if they do not use the link character when they log in their second account, it ends up creating 2 accounts for the same person.

In the admin of seat, you can move characters back into the first character group, however the billing tool does not use this so it duplicates users making the individual, corp and alliance aggregates incorrect.

https://i.imgur.com/WnMHNwE.png

the above link is an example of this. All these characters have been moved back into 1 single group.

**Comment by dysath** [comment]
So, after checking on this and being able to replicate the behavior, the problem is not in seat-billing, but rather in SeAT itself.  I've put in an issue for the main project to correct the behavior.

In the interim, you can do the following:

Get the character_id of the toon that you linked to another account (ie. 00101011)
Log into the database
Delete the columns from user_settings that have the character_id set to your toon:
    delete from user_settings where character_id=00101011

This will fix the duplicate entries on the billing app.
